format = "tuna"
type = "DATA"

[world]
start = "YOUR_ROOM"

# your room
[[rooms]]
label = "YOUR_ROOM"
name = "your bedroom"
description = '''
You are standing in your bedroom. Perhaps you are a young person who only now, on your 13th birthday, will receive a
name. You have a pretty window in the corner overlooking the world outside. There's a door leading to your bathroom to
the east, and a door leading to the hall to the south.
'''

[[rooms.exits]]
destLabel = "BATHROOM"
description = "your bathroom door"
aliases = ["BATHROOM", "TOILET", "DOOR", "EAST", ]
travelMessage = "You go through the door and enter the bathroom."

[[rooms.exits]]
destLabel = "HALLWAY"
description = "the door to the hall"
aliases = ["HALLWAY", "HALL", "OUT", "SOUTH"]
travelMessage = "You shut the door behind you as you go into the hall."

[[rooms.items]]
label = "POGO_HAMMER"
name = "a pogo hammer"
aliases = ["HAMMER", "POGOHAMMER", "POGO", "POGO_HAMMER"]
description = '''
Your treasured hammer mixed with a pogo stick. This probably shouldn't be left where children can reach it (that's a
quip, not a game mechanic).
'''


# bathroom
[[rooms]]
label = "BATHROOM"
name = "your ensuite bathroom"
description = '''
You are in the bathroom attached to your bedroom. There's a toilet, pristine due to your constant efforts to keep it
clean, next to a sink and bathtub. You enjoy having your amenities not be a complete mess. The currently closed door to
the west leads back to your bedroom.
'''

[[rooms.exits]]
destLabel = "YOUR_ROOM"
description = "the door"
aliases = ["BEDROOM", "ROOM", "DOOR", "WEST"]
travelMessage = "You head back into the bedroom."


# hallway
[[rooms]]
label = "HALLWAY"
name = "the main hallway in your house"
description = '''
This is the main hallway in your house that connects the bedrooms with the living room and kitchen. There's a doorway at
the end, but it seems boarded up, and you're pretty sure that's because it represents the limits of the game you're in.
I guess you're stuck here. In your home. Housetrapped.\n\nAnyways, there's also your bedroom door at the north end.
'''

[[rooms.exits]]
destLabel = "YOUR_ROOM"
description = "the door to your bedroom"
aliases = ["BEDROOM", "ROOM", "NORTH"]
travelMessage = "You step into your bedroom, closing the door behind you for privacy."